### ISSUE TITLE
Use markdown for mchat filetype

### ISSUE THREAD

**Issue by GordianDziwis** [gsuuon/model.nvim#54]
With the params as YAML front matter, the system prompt as a quoted block and the messages separated by `>>>` the syntax highlighting comes free with tree-sitter.

Also, nested code blocks with syntax highlighting are possible!

Here is an example how the mchat file could look like:

![image](https://github.com/gsuuon/model.nvim/assets/3330855/6e7ba859-b41b-4f8c-a6a9-9eb453afd64d)

**Comment by gsuuon** [comment]
Sorry for the late response - I originally wanted something that looked a lot like that, but ended up not going that direction just because JSON parsing comes free with neovim and I didn't want to implement a YAML parser or require luarocks to bring something in. If there's another way to get something that looks like this I'd take a PR!

I think it should be (somewhat?) straightforward to get markdown highlighting via treesitter with the current mchat syntax, would also happily take a PR for this as well (#44).

I didn't go with the explicit roles because these chats are meant to be portable across LLM's, and the role title changes so they end up needing to be converted at some point. It might make sense to allow opting in to explicitly sitting the role for LLMs with more than one though..

**Comment by GordianDziwis** [comment]
Do not be sorry, I am thankful for this nice piece of software and that you reply it all, is an amazing thing and gives me hope for humanity.

Ok, a YAML preamble is out.
 
But providing a file `ftplugin/mchat.luat` with the content:

```lua
vim.treesitter.start(0, 'markdown')
vim.bo[0].syntax = 'on'
vim.opt_local.conceallevel = 2
```

Changing the separator from `=====` to `>>>` and inserting newlines before and after the separator would be all what is needed, to achieve the look from the op.

The roles would be there only for parsing, so that it does not break, when the llm returns a markdown document with `>>>`.

I do not have currently time for an PR, I will do it when it annoys me enough.

**Comment by gsuuon** [comment]
Glad you're enjoying the plugin! I think moving to treesitter is the right step generally and was my original intent - I've been taking another look at #44, I'll see if I can get something working soonish.

**Comment by gsuuon** [comment]
Closing in favor of #44

**Comment by gsuuon** [comment]
Closing in favor of #44

**Comment by gsuuon** [comment]
Closing in favor of #44
